### ISSUE TITLE
Request to use your vpn file as a Ip blocking list

### ISSUE THREAD

**Issue by ebe76** [X4BNet/lists_vpn#54]
Hi, thx for the VPN list. Very usefull for me.

**Comment by jbreed** [comment]
I was thinking about the same thing; however, looking at some HTTPS VPN services (hard to block) the best method for blocking is hammering their IP addresses into blacklisting. This requires an automated process for keeping these updated as I just blocked the free endpoints of an app my daughter uses and each of those addresses I don't see in this list. 

I did some review of this and am looking at possibly contributing with some mechanisms for automating this specifically for HTTPS VPN providers as the normal VPN ports are easy to just block.

Commented on a post here: 
https://www.reddit.com/r/fortinet/comments/126n74d/how_can_i_block_vpns_once_and_for_all/?sort=new

I would be open to contributing some work on spare time for a mechanism that can track these with minimal maintenance over time. If it requires constant changes due to these vendors actively working to bypass, would be hard to do this with a small group for open source efforts. I know I would be open to subscribing to known feeds of VPN endpoints that is good and doesn't block other stuff.

**Comment by splitice** [comment]
In my experience the best way to block all vpns is very situational dependent. Basically it comes down to your willingness to also block server networks.

If you arent willing to do that you will probably get 10% at most. That's why the datacenters list exists.

**Comment by ebe76** [comment]
i wrote i little windows command script to add this file like it is now to windows defender firewall blocking rules, better solution.

**Comment by CameronMunroe** [comment]
> i wrote a little windows command script to add this file like it is now to windows defender firewall blocking rules, better solution.

I am not sure that is 100% suggestible. 

You likely will be blocking lots of good services beyond just VPNs.

**Comment by ebe76** [comment]
VPN Ips are blocked for a specific application from incoming traffic.
